# Generated by Django 3.0.6 on 2020-07-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=30, unique=True, verbose_name='The types of the projects')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='-', max_length=20, verbose_name='Owner')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'UserImage',
                'verbose_name_plural': 'UserImages',
            },
        ),
        migrations.CreateModel(
            name='UserProjectPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, unique=True, verbose_name='owner')),
                ('pdf', models.FileField(unique=True, upload_to='pdf/', verbose_name='pdf')),
            ],
            options={
                'db_table': 'userpdf',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='The author of the entry')),
                ('name', models.CharField(default='-', max_length=200, null=True, unique=True, verbose_name='Name of the project')),
                ('description', models.CharField(default='-', max_length=400, verbose_name='Description of the projects')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Making time')),
                ('projecttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='backloggerapp.ProjectTypes')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_entry', models.CharField(default='-', max_length=200, null=True, unique=True)),
                ('description', models.TextField(default='-', max_length=400, verbose_name='Description')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Making time')),
                ('project_of_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backloggerapp.Project', to_field='name')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-time'],
            },
        ),
    ]
