# Generated by Django 3.0.6 on 2020-07-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backloggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_plan',
            field=models.CharField(default=1, max_length=1000, verbose_name='Plan of the project'),
            preserve_default=False,
        ),
    ]
